version: 2
updates:
  - directory: "/"
    open-pull-requests-limit: 5
    package-ecosystem: "nuget"
    rebase-strategy: auto
    schedule:
      interval: "weekly"
      day: "monday"
      timezone: "America/New_York"
      time: "09:00"
