// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0
//
// Code generated with OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Vault.Api;
using Vault.Model;
using Vault.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Vault.Test.Model
{
    /// <summary>
    ///  Class for testing AliCloudWriteRoleRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AliCloudWriteRoleRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AliCloudWriteRoleRequest
        //private AliCloudWriteRoleRequest instance;

        public AliCloudWriteRoleRequestTests()
        {
            // TODO uncomment below to create an instance of AliCloudWriteRoleRequest
            //instance = new AliCloudWriteRoleRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AliCloudWriteRoleRequest
        /// </summary>
        [Fact]
        public void AliCloudWriteRoleRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" AliCloudWriteRoleRequest
            //Assert.IsType<AliCloudWriteRoleRequest>(instance);
        }


        /// <summary>
        /// Test the property 'InlinePolicies'
        /// </summary>
        [Fact]
        public void InlinePoliciesTest()
        {
            // TODO unit test for the property 'InlinePolicies'
        }
        /// <summary>
        /// Test the property 'MaxTtl'
        /// </summary>
        [Fact]
        public void MaxTtlTest()
        {
            // TODO unit test for the property 'MaxTtl'
        }
        /// <summary>
        /// Test the property 'RemotePolicies'
        /// </summary>
        [Fact]
        public void RemotePoliciesTest()
        {
            // TODO unit test for the property 'RemotePolicies'
        }
        /// <summary>
        /// Test the property 'RoleArn'
        /// </summary>
        [Fact]
        public void RoleArnTest()
        {
            // TODO unit test for the property 'RoleArn'
        }
        /// <summary>
        /// Test the property 'Ttl'
        /// </summary>
        [Fact]
        public void TtlTest()
        {
            // TODO unit test for the property 'Ttl'
        }

    }

}
