// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0
//
// Code generated with OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Vault.Api;
using Vault.Model;
using Vault.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Vault.Test.Model
{
    /// <summary>
    ///  Class for testing AliCloudWriteConfigRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AliCloudWriteConfigRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AliCloudWriteConfigRequest
        //private AliCloudWriteConfigRequest instance;

        public AliCloudWriteConfigRequestTests()
        {
            // TODO uncomment below to create an instance of AliCloudWriteConfigRequest
            //instance = new AliCloudWriteConfigRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AliCloudWriteConfigRequest
        /// </summary>
        [Fact]
        public void AliCloudWriteConfigRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" AliCloudWriteConfigRequest
            //Assert.IsType<AliCloudWriteConfigRequest>(instance);
        }


        /// <summary>
        /// Test the property 'AccessKey'
        /// </summary>
        [Fact]
        public void AccessKeyTest()
        {
            // TODO unit test for the property 'AccessKey'
        }
        /// <summary>
        /// Test the property 'SecretKey'
        /// </summary>
        [Fact]
        public void SecretKeyTest()
        {
            // TODO unit test for the property 'SecretKey'
        }

    }

}
