// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0
//
// Code generated with OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Vault.Api;
using Vault.Model;
using Vault.Client;
using System.Reflection;
using Newtonsoft.Json;



namespace Vault.Test.Model
{
    /// <summary>
    ///  Class for testing AliCloudLoginRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AliCloudLoginRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AliCloudLoginRequest
        //private AliCloudLoginRequest instance;

        public AliCloudLoginRequestTests()
        {
            // TODO uncomment below to create an instance of AliCloudLoginRequest
            //instance = new AliCloudLoginRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AliCloudLoginRequest
        /// </summary>
        [Fact]
        public void AliCloudLoginRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" AliCloudLoginRequest
            //Assert.IsType<AliCloudLoginRequest>(instance);
        }




        /// <summary>
        /// Test the property 'IdentityRequestHeaders'
        /// </summary>
        [Fact]
        public void IdentityRequestHeadersTest()
        {
            // TODO unit test for the property 'IdentityRequestHeaders'
        }

        /// <summary>
        /// Test the property 'IdentityRequestUrl'
        /// </summary>
        [Fact]
        public void IdentityRequestUrlTest()
        {
            // TODO unit test for the property 'IdentityRequestUrl'
        }

        /// <summary>
        /// Test the property 'Role'
        /// </summary>
        [Fact]
        public void RoleTest()
        {
            // TODO unit test for the property 'Role'
        }


    }

}


