// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0
//
// Code generated with OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Vault.Api;
using Vault.Model;
using Vault.Client;
using System.Reflection;
using Newtonsoft.Json;



namespace Vault.Test.Model
{
    /// <summary>
    ///  Class for testing AppRoleReadSecretIdBoundCidrsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AppRoleReadSecretIdBoundCidrsResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AppRoleReadSecretIdBoundCidrsResponse
        //private AppRoleReadSecretIdBoundCidrsResponse instance;

        public AppRoleReadSecretIdBoundCidrsResponseTests()
        {
            // TODO uncomment below to create an instance of AppRoleReadSecretIdBoundCidrsResponse
            //instance = new AppRoleReadSecretIdBoundCidrsResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AppRoleReadSecretIdBoundCidrsResponse
        /// </summary>
        [Fact]
        public void AppRoleReadSecretIdBoundCidrsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" AppRoleReadSecretIdBoundCidrsResponse
            //Assert.IsType<AppRoleReadSecretIdBoundCidrsResponse>(instance);
        }




        /// <summary>
        /// Test the property 'SecretIdBoundCidrs'
        /// </summary>
        [Fact]
        public void SecretIdBoundCidrsTest()
        {
            // TODO unit test for the property 'SecretIdBoundCidrs'
        }


    }

}


