// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0
//
// Code generated with OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Vault.Api;
using Vault.Model;
using Vault.Client;
using System.Reflection;
using Newtonsoft.Json;



namespace Vault.Test.Model
{
    /// <summary>
    ///  Class for testing AppRoleLookUpSecretIdByAccessorResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AppRoleLookUpSecretIdByAccessorResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AppRoleLookUpSecretIdByAccessorResponse
        //private AppRoleLookUpSecretIdByAccessorResponse instance;

        public AppRoleLookUpSecretIdByAccessorResponseTests()
        {
            // TODO uncomment below to create an instance of AppRoleLookUpSecretIdByAccessorResponse
            //instance = new AppRoleLookUpSecretIdByAccessorResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AppRoleLookUpSecretIdByAccessorResponse
        /// </summary>
        [Fact]
        public void AppRoleLookUpSecretIdByAccessorResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" AppRoleLookUpSecretIdByAccessorResponse
            //Assert.IsType<AppRoleLookUpSecretIdByAccessorResponse>(instance);
        }




        /// <summary>
        /// Test the property 'CidrList'
        /// </summary>
        [Fact]
        public void CidrListTest()
        {
            // TODO unit test for the property 'CidrList'
        }

        /// <summary>
        /// Test the property 'CreationTime'
        /// </summary>
        [Fact]
        public void CreationTimeTest()
        {
            // TODO unit test for the property 'CreationTime'
        }

        /// <summary>
        /// Test the property 'ExpirationTime'
        /// </summary>
        [Fact]
        public void ExpirationTimeTest()
        {
            // TODO unit test for the property 'ExpirationTime'
        }

        /// <summary>
        /// Test the property 'LastUpdatedTime'
        /// </summary>
        [Fact]
        public void LastUpdatedTimeTest()
        {
            // TODO unit test for the property 'LastUpdatedTime'
        }

        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Fact]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }

        /// <summary>
        /// Test the property 'SecretIdAccessor'
        /// </summary>
        [Fact]
        public void SecretIdAccessorTest()
        {
            // TODO unit test for the property 'SecretIdAccessor'
        }

        /// <summary>
        /// Test the property 'SecretIdNumUses'
        /// </summary>
        [Fact]
        public void SecretIdNumUsesTest()
        {
            // TODO unit test for the property 'SecretIdNumUses'
        }

        /// <summary>
        /// Test the property 'SecretIdTtl'
        /// </summary>
        [Fact]
        public void SecretIdTtlTest()
        {
            // TODO unit test for the property 'SecretIdTtl'
        }

        /// <summary>
        /// Test the property 'TokenBoundCidrs'
        /// </summary>
        [Fact]
        public void TokenBoundCidrsTest()
        {
            // TODO unit test for the property 'TokenBoundCidrs'
        }


    }

}


