// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.13.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Vault.Api;
using Vault.Model;
using Vault.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Vault.Test.Model
{
    /// <summary>
    ///  Class for testing AppRoleWriteTokenNumUsesRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AppRoleWriteTokenNumUsesRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AppRoleWriteTokenNumUsesRequest
        //private AppRoleWriteTokenNumUsesRequest instance;

        public AppRoleWriteTokenNumUsesRequestTests()
        {
            // TODO uncomment below to create an instance of AppRoleWriteTokenNumUsesRequest
            //instance = new AppRoleWriteTokenNumUsesRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AppRoleWriteTokenNumUsesRequest
        /// </summary>
        [Fact]
        public void AppRoleWriteTokenNumUsesRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" AppRoleWriteTokenNumUsesRequest
            //Assert.IsType<AppRoleWriteTokenNumUsesRequest>(instance);
        }


        /// <summary>
        /// Test the property 'TokenNumUses'
        /// </summary>
        [Fact]
        public void TokenNumUsesTest()
        {
            // TODO unit test for the property 'TokenNumUses'
        }

    }

}
