/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.13.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Vault.Api;
using Vault.Model;
using Vault.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Vault.Test.Model
{
    /// <summary>
    ///  Class for testing ApproleRoleResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ApproleRoleResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ApproleRoleResponse
        //private ApproleRoleResponse instance;

        public ApproleRoleResponseTests()
        {
            // TODO uncomment below to create an instance of ApproleRoleResponse
            //instance = new ApproleRoleResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ApproleRoleResponse
        /// </summary>
        [Fact]
        public void ApproleRoleResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ApproleRoleResponse
            //Assert.IsType<ApproleRoleResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Keys'
        /// </summary>
        [Fact]
        public void KeysTest()
        {
            // TODO unit test for the property 'Keys'
        }

    }

}
