/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.13.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Vault.Api;
using Vault.Model;
using Vault.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Vault.Test.Model
{
    /// <summary>
    ///  Class for testing AWSConfigWriteIdentityWhiteListRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AWSConfigWriteIdentityWhiteListRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AWSConfigWriteIdentityWhiteListRequest
        //private AWSConfigWriteIdentityWhiteListRequest instance;

        public AWSConfigWriteIdentityWhiteListRequestTests()
        {
            // TODO uncomment below to create an instance of AWSConfigWriteIdentityWhiteListRequest
            //instance = new AWSConfigWriteIdentityWhiteListRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AWSConfigWriteIdentityWhiteListRequest
        /// </summary>
        [Fact]
        public void AWSConfigWriteIdentityWhiteListRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" AWSConfigWriteIdentityWhiteListRequest
            //Assert.IsType<AWSConfigWriteIdentityWhiteListRequest>(instance);
        }


        /// <summary>
        /// Test the property 'DisablePeriodicTidy'
        /// </summary>
        [Fact]
        public void DisablePeriodicTidyTest()
        {
            // TODO unit test for the property 'DisablePeriodicTidy'
        }
        /// <summary>
        /// Test the property 'SafetyBuffer'
        /// </summary>
        [Fact]
        public void SafetyBufferTest()
        {
            // TODO unit test for the property 'SafetyBuffer'
        }

    }

}
