// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0
//
// Code generated with OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Vault.Api;
using Vault.Model;
using Vault.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Vault.Test.Model
{
    /// <summary>
    ///  Class for testing AWSWriteSecurityTokenServiceRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AWSWriteSecurityTokenServiceRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AWSWriteSecurityTokenServiceRequest
        //private AWSWriteSecurityTokenServiceRequest instance;

        public AWSWriteSecurityTokenServiceRequestTests()
        {
            // TODO uncomment below to create an instance of AWSWriteSecurityTokenServiceRequest
            //instance = new AWSWriteSecurityTokenServiceRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AWSWriteSecurityTokenServiceRequest
        /// </summary>
        [Fact]
        public void AWSWriteSecurityTokenServiceRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" AWSWriteSecurityTokenServiceRequest
            //Assert.IsType<AWSWriteSecurityTokenServiceRequest>(instance);
        }


        /// <summary>
        /// Test the property 'RoleArn'
        /// </summary>
        [Fact]
        public void RoleArnTest()
        {
            // TODO unit test for the property 'RoleArn'
        }
        /// <summary>
        /// Test the property 'RoleSessionName'
        /// </summary>
        [Fact]
        public void RoleSessionNameTest()
        {
            // TODO unit test for the property 'RoleSessionName'
        }
        /// <summary>
        /// Test the property 'Ttl'
        /// </summary>
        [Fact]
        public void TtlTest()
        {
            // TODO unit test for the property 'Ttl'
        }

    }

}
