// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0
//
// Code generated with OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Vault.Api;
using Vault.Model;
using Vault.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Vault.Test.Model
{
    /// <summary>
    ///  Class for testing DatabaseWriteConfigRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DatabaseWriteConfigRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DatabaseWriteConfigRequest
        //private DatabaseWriteConfigRequest instance;

        public DatabaseWriteConfigRequestTests()
        {
            // TODO uncomment below to create an instance of DatabaseWriteConfigRequest
            //instance = new DatabaseWriteConfigRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DatabaseWriteConfigRequest
        /// </summary>
        [Fact]
        public void DatabaseWriteConfigRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" DatabaseWriteConfigRequest
            //Assert.IsType<DatabaseWriteConfigRequest>(instance);
        }


        /// <summary>
        /// Test the property 'AllowedRoles'
        /// </summary>
        [Fact]
        public void AllowedRolesTest()
        {
            // TODO unit test for the property 'AllowedRoles'
        }
        /// <summary>
        /// Test the property 'PasswordPolicy'
        /// </summary>
        [Fact]
        public void PasswordPolicyTest()
        {
            // TODO unit test for the property 'PasswordPolicy'
        }
        /// <summary>
        /// Test the property 'PluginName'
        /// </summary>
        [Fact]
        public void PluginNameTest()
        {
            // TODO unit test for the property 'PluginName'
        }
        /// <summary>
        /// Test the property 'PluginVersion'
        /// </summary>
        [Fact]
        public void PluginVersionTest()
        {
            // TODO unit test for the property 'PluginVersion'
        }
        /// <summary>
        /// Test the property 'RootRotationStatements'
        /// </summary>
        [Fact]
        public void RootRotationStatementsTest()
        {
            // TODO unit test for the property 'RootRotationStatements'
        }
        /// <summary>
        /// Test the property 'VerifyConnection'
        /// </summary>
        [Fact]
        public void VerifyConnectionTest()
        {
            // TODO unit test for the property 'VerifyConnection'
        }

    }

}
