/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.12.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Vault.Api;
using Vault.Model;
using Vault.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Vault.Test.Model
{
    /// <summary>
    ///  Class for testing GcpStaticAccountRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GcpStaticAccountRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GcpStaticAccountRequest
        //private GcpStaticAccountRequest instance;

        public GcpStaticAccountRequestTests()
        {
            // TODO uncomment below to create an instance of GcpStaticAccountRequest
            //instance = new GcpStaticAccountRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GcpStaticAccountRequest
        /// </summary>
        [Fact]
        public void GcpStaticAccountRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" GcpStaticAccountRequest
            //Assert.IsType<GcpStaticAccountRequest>(instance);
        }


        /// <summary>
        /// Test the property 'Bindings'
        /// </summary>
        [Fact]
        public void BindingsTest()
        {
            // TODO unit test for the property 'Bindings'
        }
        /// <summary>
        /// Test the property 'SecretType'
        /// </summary>
        [Fact]
        public void SecretTypeTest()
        {
            // TODO unit test for the property 'SecretType'
        }
        /// <summary>
        /// Test the property 'ServiceAccountEmail'
        /// </summary>
        [Fact]
        public void ServiceAccountEmailTest()
        {
            // TODO unit test for the property 'ServiceAccountEmail'
        }
        /// <summary>
        /// Test the property 'TokenScopes'
        /// </summary>
        [Fact]
        public void TokenScopesTest()
        {
            // TODO unit test for the property 'TokenScopes'
        }

    }

}
