// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0
//
// Code generated with OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Vault.Api;
using Vault.Model;
using Vault.Client;
using System.Reflection;
using Newtonsoft.Json;



namespace Vault.Test.Model
{
    /// <summary>
    ///  Class for testing GenerateRandomWithSourceRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GenerateRandomWithSourceRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GenerateRandomWithSourceRequest
        //private GenerateRandomWithSourceRequest instance;

        public GenerateRandomWithSourceRequestTests()
        {
            // TODO uncomment below to create an instance of GenerateRandomWithSourceRequest
            //instance = new GenerateRandomWithSourceRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GenerateRandomWithSourceRequest
        /// </summary>
        [Fact]
        public void GenerateRandomWithSourceRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" GenerateRandomWithSourceRequest
            //Assert.IsType<GenerateRandomWithSourceRequest>(instance);
        }




        /// <summary>
        /// Test the property 'Bytes'
        /// </summary>
        [Fact]
        public void BytesTest()
        {
            // TODO unit test for the property 'Bytes'
        }

        /// <summary>
        /// Test the property 'Format'
        /// </summary>
        [Fact]
        public void FormatTest()
        {
            // TODO unit test for the property 'Format'
        }

        /// <summary>
        /// Test the property 'Urlbytes'
        /// </summary>
        [Fact]
        public void UrlbytesTest()
        {
            // TODO unit test for the property 'Urlbytes'
        }


    }

}


