// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0
//
// Code generated with OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Vault.Api;
using Vault.Model;
using Vault.Client;
using System.Reflection;
using Newtonsoft.Json;



namespace Vault.Test.Model
{
    /// <summary>
    ///  Class for testing GoogleCloudKmsReencryptRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GoogleCloudKmsReencryptRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GoogleCloudKmsReencryptRequest
        //private GoogleCloudKmsReencryptRequest instance;

        public GoogleCloudKmsReencryptRequestTests()
        {
            // TODO uncomment below to create an instance of GoogleCloudKmsReencryptRequest
            //instance = new GoogleCloudKmsReencryptRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GoogleCloudKmsReencryptRequest
        /// </summary>
        [Fact]
        public void GoogleCloudKmsReencryptRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" GoogleCloudKmsReencryptRequest
            //Assert.IsType<GoogleCloudKmsReencryptRequest>(instance);
        }




        /// <summary>
        /// Test the property 'AdditionalAuthenticatedData'
        /// </summary>
        [Fact]
        public void AdditionalAuthenticatedDataTest()
        {
            // TODO unit test for the property 'AdditionalAuthenticatedData'
        }

        /// <summary>
        /// Test the property 'Ciphertext'
        /// </summary>
        [Fact]
        public void CiphertextTest()
        {
            // TODO unit test for the property 'Ciphertext'
        }

        /// <summary>
        /// Test the property 'KeyVersion'
        /// </summary>
        [Fact]
        public void KeyVersionTest()
        {
            // TODO unit test for the property 'KeyVersion'
        }


    }

}


