// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0
//
// Code generated with OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Vault.Api;
using Vault.Model;
using Vault.Client;
using System.Reflection;
using Newtonsoft.Json;



namespace Vault.Test.Model
{
    /// <summary>
    ///  Class for testing GoogleCloudKmsWriteKeyRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GoogleCloudKmsWriteKeyRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GoogleCloudKmsWriteKeyRequest
        //private GoogleCloudKmsWriteKeyRequest instance;

        public GoogleCloudKmsWriteKeyRequestTests()
        {
            // TODO uncomment below to create an instance of GoogleCloudKmsWriteKeyRequest
            //instance = new GoogleCloudKmsWriteKeyRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GoogleCloudKmsWriteKeyRequest
        /// </summary>
        [Fact]
        public void GoogleCloudKmsWriteKeyRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" GoogleCloudKmsWriteKeyRequest
            //Assert.IsType<GoogleCloudKmsWriteKeyRequest>(instance);
        }




        /// <summary>
        /// Test the property 'Algorithm'
        /// </summary>
        [Fact]
        public void AlgorithmTest()
        {
            // TODO unit test for the property 'Algorithm'
        }

        /// <summary>
        /// Test the property 'CryptoKey'
        /// </summary>
        [Fact]
        public void CryptoKeyTest()
        {
            // TODO unit test for the property 'CryptoKey'
        }

        /// <summary>
        /// Test the property 'KeyRing'
        /// </summary>
        [Fact]
        public void KeyRingTest()
        {
            // TODO unit test for the property 'KeyRing'
        }

        /// <summary>
        /// Test the property 'Labels'
        /// </summary>
        [Fact]
        public void LabelsTest()
        {
            // TODO unit test for the property 'Labels'
        }

        /// <summary>
        /// Test the property 'ProtectionLevel'
        /// </summary>
        [Fact]
        public void ProtectionLevelTest()
        {
            // TODO unit test for the property 'ProtectionLevel'
        }

        /// <summary>
        /// Test the property 'Purpose'
        /// </summary>
        [Fact]
        public void PurposeTest()
        {
            // TODO unit test for the property 'Purpose'
        }

        /// <summary>
        /// Test the property 'RotationPeriod'
        /// </summary>
        [Fact]
        public void RotationPeriodTest()
        {
            // TODO unit test for the property 'RotationPeriod'
        }


    }

}


