// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0
//
// Code generated with OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Vault.Api;
using Vault.Model;
using Vault.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Vault.Test.Model
{
    /// <summary>
    ///  Class for testing GoogleCloudWriteRoleServiceAccountsRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GoogleCloudWriteRoleServiceAccountsRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GoogleCloudWriteRoleServiceAccountsRequest
        //private GoogleCloudWriteRoleServiceAccountsRequest instance;

        public GoogleCloudWriteRoleServiceAccountsRequestTests()
        {
            // TODO uncomment below to create an instance of GoogleCloudWriteRoleServiceAccountsRequest
            //instance = new GoogleCloudWriteRoleServiceAccountsRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GoogleCloudWriteRoleServiceAccountsRequest
        /// </summary>
        [Fact]
        public void GoogleCloudWriteRoleServiceAccountsRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" GoogleCloudWriteRoleServiceAccountsRequest
            //Assert.IsType<GoogleCloudWriteRoleServiceAccountsRequest>(instance);
        }


        /// <summary>
        /// Test the property 'Add'
        /// </summary>
        [Fact]
        public void AddTest()
        {
            // TODO unit test for the property 'Add'
        }
        /// <summary>
        /// Test the property 'Remove'
        /// </summary>
        [Fact]
        public void RemoveTest()
        {
            // TODO unit test for the property 'Remove'
        }

    }

}
