/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.13.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Vault.Api;
using Vault.Model;
using Vault.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Vault.Test.Model
{
    /// <summary>
    ///  Class for testing JwtOidcCallbackRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class JwtOidcCallbackRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for JwtOidcCallbackRequest
        //private JwtOidcCallbackRequest instance;

        public JwtOidcCallbackRequestTests()
        {
            // TODO uncomment below to create an instance of JwtOidcCallbackRequest
            //instance = new JwtOidcCallbackRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of JwtOidcCallbackRequest
        /// </summary>
        [Fact]
        public void JwtOidcCallbackRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" JwtOidcCallbackRequest
            //Assert.IsType<JwtOidcCallbackRequest>(instance);
        }


        /// <summary>
        /// Test the property 'ClientNonce'
        /// </summary>
        [Fact]
        public void ClientNonceTest()
        {
            // TODO unit test for the property 'ClientNonce'
        }
        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }
        /// <summary>
        /// Test the property 'IdToken'
        /// </summary>
        [Fact]
        public void IdTokenTest()
        {
            // TODO unit test for the property 'IdToken'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Fact]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }

    }

}
