// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0
//
// Code generated with OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Vault.Api;
using Vault.Model;
using Vault.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Vault.Test.Model
{
    /// <summary>
    ///  Class for testing KVv2DeleteVersionsRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class KVv2DeleteVersionsRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for KVv2DeleteVersionsRequest
        //private KVv2DeleteVersionsRequest instance;

        public KVv2DeleteVersionsRequestTests()
        {
            // TODO uncomment below to create an instance of KVv2DeleteVersionsRequest
            //instance = new KVv2DeleteVersionsRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of KVv2DeleteVersionsRequest
        /// </summary>
        [Fact]
        public void KVv2DeleteVersionsRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" KVv2DeleteVersionsRequest
            //Assert.IsType<KVv2DeleteVersionsRequest>(instance);
        }


        /// <summary>
        /// Test the property 'Versions'
        /// </summary>
        [Fact]
        public void VersionsTest()
        {
            // TODO unit test for the property 'Versions'
        }

    }

}
