// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0
//
// Code generated with OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Vault.Api;
using Vault.Model;
using Vault.Client;
using System.Reflection;
using Newtonsoft.Json;



namespace Vault.Test.Model
{
    /// <summary>
    ///  Class for testing KvV2UndeleteVersionsRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class KvV2UndeleteVersionsRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for KvV2UndeleteVersionsRequest
        //private KvV2UndeleteVersionsRequest instance;

        public KvV2UndeleteVersionsRequestTests()
        {
            // TODO uncomment below to create an instance of KvV2UndeleteVersionsRequest
            //instance = new KvV2UndeleteVersionsRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of KvV2UndeleteVersionsRequest
        /// </summary>
        [Fact]
        public void KvV2UndeleteVersionsRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" KvV2UndeleteVersionsRequest
            //Assert.IsType<KvV2UndeleteVersionsRequest>(instance);
        }




        /// <summary>
        /// Test the property 'Versions'
        /// </summary>
        [Fact]
        public void VersionsTest()
        {
            // TODO unit test for the property 'Versions'
        }


    }

}


