// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0
//
// Code generated with OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Vault.Api;
using Vault.Model;
using Vault.Client;
using System.Reflection;
using Newtonsoft.Json;



namespace Vault.Test.Model
{
    /// <summary>
    ///  Class for testing LdapWriteUserRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LdapWriteUserRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LdapWriteUserRequest
        //private LdapWriteUserRequest instance;

        public LdapWriteUserRequestTests()
        {
            // TODO uncomment below to create an instance of LdapWriteUserRequest
            //instance = new LdapWriteUserRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LdapWriteUserRequest
        /// </summary>
        [Fact]
        public void LdapWriteUserRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" LdapWriteUserRequest
            //Assert.IsType<LdapWriteUserRequest>(instance);
        }




        /// <summary>
        /// Test the property 'Groups'
        /// </summary>
        [Fact]
        public void GroupsTest()
        {
            // TODO unit test for the property 'Groups'
        }

        /// <summary>
        /// Test the property 'Policies'
        /// </summary>
        [Fact]
        public void PoliciesTest()
        {
            // TODO unit test for the property 'Policies'
        }


    }

}


