// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0
//
// Code generated with OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Vault.Api;
using Vault.Model;
using Vault.Client;
using System.Reflection;
using Newtonsoft.Json;



namespace Vault.Test.Model
{
    /// <summary>
    ///  Class for testing LeaderStatusResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LeaderStatusResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LeaderStatusResponse
        //private LeaderStatusResponse instance;

        public LeaderStatusResponseTests()
        {
            // TODO uncomment below to create an instance of LeaderStatusResponse
            //instance = new LeaderStatusResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LeaderStatusResponse
        /// </summary>
        [Fact]
        public void LeaderStatusResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" LeaderStatusResponse
            //Assert.IsType<LeaderStatusResponse>(instance);
        }




        /// <summary>
        /// Test the property 'ActiveTime'
        /// </summary>
        [Fact]
        public void ActiveTimeTest()
        {
            // TODO unit test for the property 'ActiveTime'
        }

        /// <summary>
        /// Test the property 'HaEnabled'
        /// </summary>
        [Fact]
        public void HaEnabledTest()
        {
            // TODO unit test for the property 'HaEnabled'
        }

        /// <summary>
        /// Test the property 'IsSelf'
        /// </summary>
        [Fact]
        public void IsSelfTest()
        {
            // TODO unit test for the property 'IsSelf'
        }

        /// <summary>
        /// Test the property 'LastWal'
        /// </summary>
        [Fact]
        public void LastWalTest()
        {
            // TODO unit test for the property 'LastWal'
        }

        /// <summary>
        /// Test the property 'LeaderAddress'
        /// </summary>
        [Fact]
        public void LeaderAddressTest()
        {
            // TODO unit test for the property 'LeaderAddress'
        }

        /// <summary>
        /// Test the property 'LeaderClusterAddress'
        /// </summary>
        [Fact]
        public void LeaderClusterAddressTest()
        {
            // TODO unit test for the property 'LeaderClusterAddress'
        }

        /// <summary>
        /// Test the property 'PerformanceStandby'
        /// </summary>
        [Fact]
        public void PerformanceStandbyTest()
        {
            // TODO unit test for the property 'PerformanceStandby'
        }

        /// <summary>
        /// Test the property 'PerformanceStandbyLastRemoteWal'
        /// </summary>
        [Fact]
        public void PerformanceStandbyLastRemoteWalTest()
        {
            // TODO unit test for the property 'PerformanceStandbyLastRemoteWal'
        }

        /// <summary>
        /// Test the property 'RaftAppliedIndex'
        /// </summary>
        [Fact]
        public void RaftAppliedIndexTest()
        {
            // TODO unit test for the property 'RaftAppliedIndex'
        }

        /// <summary>
        /// Test the property 'RaftCommittedIndex'
        /// </summary>
        [Fact]
        public void RaftCommittedIndexTest()
        {
            // TODO unit test for the property 'RaftCommittedIndex'
        }


    }

}


