// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0
//
// Code generated with OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Vault.Api;
using Vault.Model;
using Vault.Client;
using System.Reflection;
using Newtonsoft.Json;



namespace Vault.Test.Model
{
    /// <summary>
    ///  Class for testing LeasesRevokeLeaseWithPrefixRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LeasesRevokeLeaseWithPrefixRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LeasesRevokeLeaseWithPrefixRequest
        //private LeasesRevokeLeaseWithPrefixRequest instance;

        public LeasesRevokeLeaseWithPrefixRequestTests()
        {
            // TODO uncomment below to create an instance of LeasesRevokeLeaseWithPrefixRequest
            //instance = new LeasesRevokeLeaseWithPrefixRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LeasesRevokeLeaseWithPrefixRequest
        /// </summary>
        [Fact]
        public void LeasesRevokeLeaseWithPrefixRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" LeasesRevokeLeaseWithPrefixRequest
            //Assert.IsType<LeasesRevokeLeaseWithPrefixRequest>(instance);
        }




        /// <summary>
        /// Test the property 'Sync'
        /// </summary>
        [Fact]
        public void SyncTest()
        {
            // TODO unit test for the property 'Sync'
        }


    }

}


