// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0
//
// Code generated with OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Vault.Api;
using Vault.Model;
using Vault.Client;
using System.Reflection;
using Newtonsoft.Json;



namespace Vault.Test.Model
{
    /// <summary>
    ///  Class for testing MfaAdminDestroyTotpSecretRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MfaAdminDestroyTotpSecretRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MfaAdminDestroyTotpSecretRequest
        //private MfaAdminDestroyTotpSecretRequest instance;

        public MfaAdminDestroyTotpSecretRequestTests()
        {
            // TODO uncomment below to create an instance of MfaAdminDestroyTotpSecretRequest
            //instance = new MfaAdminDestroyTotpSecretRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MfaAdminDestroyTotpSecretRequest
        /// </summary>
        [Fact]
        public void MfaAdminDestroyTotpSecretRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" MfaAdminDestroyTotpSecretRequest
            //Assert.IsType<MfaAdminDestroyTotpSecretRequest>(instance);
        }




        /// <summary>
        /// Test the property 'EntityId'
        /// </summary>
        [Fact]
        public void EntityIdTest()
        {
            // TODO unit test for the property 'EntityId'
        }

        /// <summary>
        /// Test the property 'MethodId'
        /// </summary>
        [Fact]
        public void MethodIdTest()
        {
            // TODO unit test for the property 'MethodId'
        }


    }

}


