// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0
//
// Code generated with OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Vault.Api;
using Vault.Model;
using Vault.Client;
using System.Reflection;
using Newtonsoft.Json;



namespace Vault.Test.Model
{
    /// <summary>
    ///  Class for testing MfaCreateTotpMethodRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MfaCreateTotpMethodRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MfaCreateTotpMethodRequest
        //private MfaCreateTotpMethodRequest instance;

        public MfaCreateTotpMethodRequestTests()
        {
            // TODO uncomment below to create an instance of MfaCreateTotpMethodRequest
            //instance = new MfaCreateTotpMethodRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MfaCreateTotpMethodRequest
        /// </summary>
        [Fact]
        public void MfaCreateTotpMethodRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" MfaCreateTotpMethodRequest
            //Assert.IsType<MfaCreateTotpMethodRequest>(instance);
        }




        /// <summary>
        /// Test the property 'Algorithm'
        /// </summary>
        [Fact]
        public void AlgorithmTest()
        {
            // TODO unit test for the property 'Algorithm'
        }

        /// <summary>
        /// Test the property 'Digits'
        /// </summary>
        [Fact]
        public void DigitsTest()
        {
            // TODO unit test for the property 'Digits'
        }

        /// <summary>
        /// Test the property 'Issuer'
        /// </summary>
        [Fact]
        public void IssuerTest()
        {
            // TODO unit test for the property 'Issuer'
        }

        /// <summary>
        /// Test the property 'KeySize'
        /// </summary>
        [Fact]
        public void KeySizeTest()
        {
            // TODO unit test for the property 'KeySize'
        }

        /// <summary>
        /// Test the property 'MaxValidationAttempts'
        /// </summary>
        [Fact]
        public void MaxValidationAttemptsTest()
        {
            // TODO unit test for the property 'MaxValidationAttempts'
        }

        /// <summary>
        /// Test the property 'MethodName'
        /// </summary>
        [Fact]
        public void MethodNameTest()
        {
            // TODO unit test for the property 'MethodName'
        }

        /// <summary>
        /// Test the property 'Period'
        /// </summary>
        [Fact]
        public void PeriodTest()
        {
            // TODO unit test for the property 'Period'
        }

        /// <summary>
        /// Test the property 'QrSize'
        /// </summary>
        [Fact]
        public void QrSizeTest()
        {
            // TODO unit test for the property 'QrSize'
        }

        /// <summary>
        /// Test the property 'Skew'
        /// </summary>
        [Fact]
        public void SkewTest()
        {
            // TODO unit test for the property 'Skew'
        }


    }

}


