// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0
//
// Code generated with OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Vault.Api;
using Vault.Model;
using Vault.Client;
using System.Reflection;
using Newtonsoft.Json;



namespace Vault.Test.Model
{
    /// <summary>
    ///  Class for testing MfaConfigureDuoMethodRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MfaConfigureDuoMethodRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MfaConfigureDuoMethodRequest
        //private MfaConfigureDuoMethodRequest instance;

        public MfaConfigureDuoMethodRequestTests()
        {
            // TODO uncomment below to create an instance of MfaConfigureDuoMethodRequest
            //instance = new MfaConfigureDuoMethodRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MfaConfigureDuoMethodRequest
        /// </summary>
        [Fact]
        public void MfaConfigureDuoMethodRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" MfaConfigureDuoMethodRequest
            //Assert.IsType<MfaConfigureDuoMethodRequest>(instance);
        }




        /// <summary>
        /// Test the property 'ApiHostname'
        /// </summary>
        [Fact]
        public void ApiHostnameTest()
        {
            // TODO unit test for the property 'ApiHostname'
        }

        /// <summary>
        /// Test the property 'IntegrationKey'
        /// </summary>
        [Fact]
        public void IntegrationKeyTest()
        {
            // TODO unit test for the property 'IntegrationKey'
        }

        /// <summary>
        /// Test the property 'MethodName'
        /// </summary>
        [Fact]
        public void MethodNameTest()
        {
            // TODO unit test for the property 'MethodName'
        }

        /// <summary>
        /// Test the property 'PushInfo'
        /// </summary>
        [Fact]
        public void PushInfoTest()
        {
            // TODO unit test for the property 'PushInfo'
        }

        /// <summary>
        /// Test the property 'SecretKey'
        /// </summary>
        [Fact]
        public void SecretKeyTest()
        {
            // TODO unit test for the property 'SecretKey'
        }

        /// <summary>
        /// Test the property 'UsePasscode'
        /// </summary>
        [Fact]
        public void UsePasscodeTest()
        {
            // TODO unit test for the property 'UsePasscode'
        }

        /// <summary>
        /// Test the property 'UsernameFormat'
        /// </summary>
        [Fact]
        public void UsernameFormatTest()
        {
            // TODO unit test for the property 'UsernameFormat'
        }


    }

}


