/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.12.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Vault.Api;
using Vault.Model;
using Vault.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Vault.Test.Model
{
    /// <summary>
    ///  Class for testing MongodbatlasRolesRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MongodbatlasRolesRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MongodbatlasRolesRequest
        //private MongodbatlasRolesRequest instance;

        public MongodbatlasRolesRequestTests()
        {
            // TODO uncomment below to create an instance of MongodbatlasRolesRequest
            //instance = new MongodbatlasRolesRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MongodbatlasRolesRequest
        /// </summary>
        [Fact]
        public void MongodbatlasRolesRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" MongodbatlasRolesRequest
            //Assert.IsType<MongodbatlasRolesRequest>(instance);
        }


        /// <summary>
        /// Test the property 'CidrBlocks'
        /// </summary>
        [Fact]
        public void CidrBlocksTest()
        {
            // TODO unit test for the property 'CidrBlocks'
        }
        /// <summary>
        /// Test the property 'IpAddresses'
        /// </summary>
        [Fact]
        public void IpAddressesTest()
        {
            // TODO unit test for the property 'IpAddresses'
        }
        /// <summary>
        /// Test the property 'MaxTtl'
        /// </summary>
        [Fact]
        public void MaxTtlTest()
        {
            // TODO unit test for the property 'MaxTtl'
        }
        /// <summary>
        /// Test the property 'OrganizationId'
        /// </summary>
        [Fact]
        public void OrganizationIdTest()
        {
            // TODO unit test for the property 'OrganizationId'
        }
        /// <summary>
        /// Test the property 'ProjectId'
        /// </summary>
        [Fact]
        public void ProjectIdTest()
        {
            // TODO unit test for the property 'ProjectId'
        }
        /// <summary>
        /// Test the property 'ProjectRoles'
        /// </summary>
        [Fact]
        public void ProjectRolesTest()
        {
            // TODO unit test for the property 'ProjectRoles'
        }
        /// <summary>
        /// Test the property 'Roles'
        /// </summary>
        [Fact]
        public void RolesTest()
        {
            // TODO unit test for the property 'Roles'
        }
        /// <summary>
        /// Test the property 'Ttl'
        /// </summary>
        [Fact]
        public void TtlTest()
        {
            // TODO unit test for the property 'Ttl'
        }

    }

}
