// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0
//
// Code generated with OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Vault.Api;
using Vault.Model;
using Vault.Client;
using System.Reflection;
using Newtonsoft.Json;



namespace Vault.Test.Model
{
    /// <summary>
    ///  Class for testing OciLoginRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OciLoginRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OciLoginRequest
        //private OciLoginRequest instance;

        public OciLoginRequestTests()
        {
            // TODO uncomment below to create an instance of OciLoginRequest
            //instance = new OciLoginRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OciLoginRequest
        /// </summary>
        [Fact]
        public void OciLoginRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" OciLoginRequest
            //Assert.IsType<OciLoginRequest>(instance);
        }




        /// <summary>
        /// Test the property 'RequestHeaders'
        /// </summary>
        [Fact]
        public void RequestHeadersTest()
        {
            // TODO unit test for the property 'RequestHeaders'
        }


    }

}


