// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0
//
// Code generated with OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Vault.Api;
using Vault.Model;
using Vault.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Vault.Test.Model
{
    /// <summary>
    ///  Class for testing OCILoginWithRoleRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OCILoginWithRoleRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OCILoginWithRoleRequest
        //private OCILoginWithRoleRequest instance;

        public OCILoginWithRoleRequestTests()
        {
            // TODO uncomment below to create an instance of OCILoginWithRoleRequest
            //instance = new OCILoginWithRoleRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OCILoginWithRoleRequest
        /// </summary>
        [Fact]
        public void OCILoginWithRoleRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" OCILoginWithRoleRequest
            //Assert.IsType<OCILoginWithRoleRequest>(instance);
        }


        /// <summary>
        /// Test the property 'RequestHeaders'
        /// </summary>
        [Fact]
        public void RequestHeadersTest()
        {
            // TODO unit test for the property 'RequestHeaders'
        }

    }

}
