// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0
//
// Code generated with OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Vault.Api;
using Vault.Model;
using Vault.Client;
using System.Reflection;
using Newtonsoft.Json;



namespace Vault.Test.Model
{
    /// <summary>
    ///  Class for testing OidcRotateKeyRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OidcRotateKeyRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OidcRotateKeyRequest
        //private OidcRotateKeyRequest instance;

        public OidcRotateKeyRequestTests()
        {
            // TODO uncomment below to create an instance of OidcRotateKeyRequest
            //instance = new OidcRotateKeyRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OidcRotateKeyRequest
        /// </summary>
        [Fact]
        public void OidcRotateKeyRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" OidcRotateKeyRequest
            //Assert.IsType<OidcRotateKeyRequest>(instance);
        }




        /// <summary>
        /// Test the property 'VerificationTtl'
        /// </summary>
        [Fact]
        public void VerificationTtlTest()
        {
            // TODO unit test for the property 'VerificationTtl'
        }


    }

}


