/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.13.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Vault.Api;
using Vault.Model;
using Vault.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Vault.Test.Model
{
    /// <summary>
    ///  Class for testing OIDCWriteAuthConfigRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OIDCWriteAuthConfigRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OIDCWriteAuthConfigRequest
        //private OIDCWriteAuthConfigRequest instance;

        public OIDCWriteAuthConfigRequestTests()
        {
            // TODO uncomment below to create an instance of OIDCWriteAuthConfigRequest
            //instance = new OIDCWriteAuthConfigRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OIDCWriteAuthConfigRequest
        /// </summary>
        [Fact]
        public void OIDCWriteAuthConfigRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" OIDCWriteAuthConfigRequest
            //Assert.IsType<OIDCWriteAuthConfigRequest>(instance);
        }


        /// <summary>
        /// Test the property 'BoundIssuer'
        /// </summary>
        [Fact]
        public void BoundIssuerTest()
        {
            // TODO unit test for the property 'BoundIssuer'
        }
        /// <summary>
        /// Test the property 'DefaultRole'
        /// </summary>
        [Fact]
        public void DefaultRoleTest()
        {
            // TODO unit test for the property 'DefaultRole'
        }
        /// <summary>
        /// Test the property 'JwksCaPem'
        /// </summary>
        [Fact]
        public void JwksCaPemTest()
        {
            // TODO unit test for the property 'JwksCaPem'
        }
        /// <summary>
        /// Test the property 'JwksUrl'
        /// </summary>
        [Fact]
        public void JwksUrlTest()
        {
            // TODO unit test for the property 'JwksUrl'
        }
        /// <summary>
        /// Test the property 'JwtSupportedAlgs'
        /// </summary>
        [Fact]
        public void JwtSupportedAlgsTest()
        {
            // TODO unit test for the property 'JwtSupportedAlgs'
        }
        /// <summary>
        /// Test the property 'JwtValidationPubkeys'
        /// </summary>
        [Fact]
        public void JwtValidationPubkeysTest()
        {
            // TODO unit test for the property 'JwtValidationPubkeys'
        }
        /// <summary>
        /// Test the property 'NamespaceInState'
        /// </summary>
        [Fact]
        public void NamespaceInStateTest()
        {
            // TODO unit test for the property 'NamespaceInState'
        }
        /// <summary>
        /// Test the property 'OidcClientId'
        /// </summary>
        [Fact]
        public void OidcClientIdTest()
        {
            // TODO unit test for the property 'OidcClientId'
        }
        /// <summary>
        /// Test the property 'OidcClientSecret'
        /// </summary>
        [Fact]
        public void OidcClientSecretTest()
        {
            // TODO unit test for the property 'OidcClientSecret'
        }
        /// <summary>
        /// Test the property 'OidcDiscoveryCaPem'
        /// </summary>
        [Fact]
        public void OidcDiscoveryCaPemTest()
        {
            // TODO unit test for the property 'OidcDiscoveryCaPem'
        }
        /// <summary>
        /// Test the property 'OidcDiscoveryUrl'
        /// </summary>
        [Fact]
        public void OidcDiscoveryUrlTest()
        {
            // TODO unit test for the property 'OidcDiscoveryUrl'
        }
        /// <summary>
        /// Test the property 'OidcResponseMode'
        /// </summary>
        [Fact]
        public void OidcResponseModeTest()
        {
            // TODO unit test for the property 'OidcResponseMode'
        }
        /// <summary>
        /// Test the property 'OidcResponseTypes'
        /// </summary>
        [Fact]
        public void OidcResponseTypesTest()
        {
            // TODO unit test for the property 'OidcResponseTypes'
        }
        /// <summary>
        /// Test the property 'ProviderConfig'
        /// </summary>
        [Fact]
        public void ProviderConfigTest()
        {
            // TODO unit test for the property 'ProviderConfig'
        }

    }

}
