// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0
//
// Code generated with OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Vault.Api;
using Vault.Model;
using Vault.Client;
using System.Reflection;
using Newtonsoft.Json;



namespace Vault.Test.Model
{
    /// <summary>
    ///  Class for testing OidcConfigureRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OidcConfigureRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OidcConfigureRequest
        //private OidcConfigureRequest instance;

        public OidcConfigureRequestTests()
        {
            // TODO uncomment below to create an instance of OidcConfigureRequest
            //instance = new OidcConfigureRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OidcConfigureRequest
        /// </summary>
        [Fact]
        public void OidcConfigureRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" OidcConfigureRequest
            //Assert.IsType<OidcConfigureRequest>(instance);
        }




        /// <summary>
        /// Test the property 'Issuer'
        /// </summary>
        [Fact]
        public void IssuerTest()
        {
            // TODO unit test for the property 'Issuer'
        }


    }

}


