// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0
//
// Code generated with OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Vault.Api;
using Vault.Model;
using Vault.Client;
using System.Reflection;
using Newtonsoft.Json;



namespace Vault.Test.Model
{
    /// <summary>
    ///  Class for testing OidcWriteProviderRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OidcWriteProviderRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OidcWriteProviderRequest
        //private OidcWriteProviderRequest instance;

        public OidcWriteProviderRequestTests()
        {
            // TODO uncomment below to create an instance of OidcWriteProviderRequest
            //instance = new OidcWriteProviderRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OidcWriteProviderRequest
        /// </summary>
        [Fact]
        public void OidcWriteProviderRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" OidcWriteProviderRequest
            //Assert.IsType<OidcWriteProviderRequest>(instance);
        }




        /// <summary>
        /// Test the property 'AllowedClientIds'
        /// </summary>
        [Fact]
        public void AllowedClientIdsTest()
        {
            // TODO unit test for the property 'AllowedClientIds'
        }

        /// <summary>
        /// Test the property 'Issuer'
        /// </summary>
        [Fact]
        public void IssuerTest()
        {
            // TODO unit test for the property 'Issuer'
        }

        /// <summary>
        /// Test the property 'ScopesSupported'
        /// </summary>
        [Fact]
        public void ScopesSupportedTest()
        {
            // TODO unit test for the property 'ScopesSupported'
        }


    }

}


