// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0
//
// Code generated with OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Vault.Api;
using Vault.Model;
using Vault.Client;
using System.Reflection;
using Newtonsoft.Json;



namespace Vault.Test.Model
{
    /// <summary>
    ///  Class for testing OktaWriteGroupRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OktaWriteGroupRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OktaWriteGroupRequest
        //private OktaWriteGroupRequest instance;

        public OktaWriteGroupRequestTests()
        {
            // TODO uncomment below to create an instance of OktaWriteGroupRequest
            //instance = new OktaWriteGroupRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OktaWriteGroupRequest
        /// </summary>
        [Fact]
        public void OktaWriteGroupRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" OktaWriteGroupRequest
            //Assert.IsType<OktaWriteGroupRequest>(instance);
        }




        /// <summary>
        /// Test the property 'Policies'
        /// </summary>
        [Fact]
        public void PoliciesTest()
        {
            // TODO unit test for the property 'Policies'
        }


    }

}


