// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0
//
// Code generated with OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Vault.Api;
using Vault.Model;
using Vault.Client;
using System.Reflection;
using Newtonsoft.Json;



namespace Vault.Test.Model
{
    /// <summary>
    ///  Class for testing PersonaUpdateByIdRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PersonaUpdateByIdRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PersonaUpdateByIdRequest
        //private PersonaUpdateByIdRequest instance;

        public PersonaUpdateByIdRequestTests()
        {
            // TODO uncomment below to create an instance of PersonaUpdateByIdRequest
            //instance = new PersonaUpdateByIdRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PersonaUpdateByIdRequest
        /// </summary>
        [Fact]
        public void PersonaUpdateByIdRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" PersonaUpdateByIdRequest
            //Assert.IsType<PersonaUpdateByIdRequest>(instance);
        }




        /// <summary>
        /// Test the property 'EntityId'
        /// </summary>
        [Fact]
        public void EntityIdTest()
        {
            // TODO unit test for the property 'EntityId'
        }

        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Fact]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }

        /// <summary>
        /// Test the property 'MountAccessor'
        /// </summary>
        [Fact]
        public void MountAccessorTest()
        {
            // TODO unit test for the property 'MountAccessor'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }


    }

}


