// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0
//
// Code generated with OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Vault.Api;
using Vault.Model;
using Vault.Client;
using System.Reflection;
using Newtonsoft.Json;



namespace Vault.Test.Model
{
    /// <summary>
    ///  Class for testing PkiGenerateRootResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PkiGenerateRootResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PkiGenerateRootResponse
        //private PkiGenerateRootResponse instance;

        public PkiGenerateRootResponseTests()
        {
            // TODO uncomment below to create an instance of PkiGenerateRootResponse
            //instance = new PkiGenerateRootResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PkiGenerateRootResponse
        /// </summary>
        [Fact]
        public void PkiGenerateRootResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" PkiGenerateRootResponse
            //Assert.IsType<PkiGenerateRootResponse>(instance);
        }




        /// <summary>
        /// Test the property 'Certificate'
        /// </summary>
        [Fact]
        public void CertificateTest()
        {
            // TODO unit test for the property 'Certificate'
        }

        /// <summary>
        /// Test the property 'Expiration'
        /// </summary>
        [Fact]
        public void ExpirationTest()
        {
            // TODO unit test for the property 'Expiration'
        }

        /// <summary>
        /// Test the property 'IssuerId'
        /// </summary>
        [Fact]
        public void IssuerIdTest()
        {
            // TODO unit test for the property 'IssuerId'
        }

        /// <summary>
        /// Test the property 'IssuerName'
        /// </summary>
        [Fact]
        public void IssuerNameTest()
        {
            // TODO unit test for the property 'IssuerName'
        }

        /// <summary>
        /// Test the property 'IssuingCa'
        /// </summary>
        [Fact]
        public void IssuingCaTest()
        {
            // TODO unit test for the property 'IssuingCa'
        }

        /// <summary>
        /// Test the property 'KeyId'
        /// </summary>
        [Fact]
        public void KeyIdTest()
        {
            // TODO unit test for the property 'KeyId'
        }

        /// <summary>
        /// Test the property 'KeyName'
        /// </summary>
        [Fact]
        public void KeyNameTest()
        {
            // TODO unit test for the property 'KeyName'
        }

        /// <summary>
        /// Test the property 'PrivateKey'
        /// </summary>
        [Fact]
        public void PrivateKeyTest()
        {
            // TODO unit test for the property 'PrivateKey'
        }

        /// <summary>
        /// Test the property 'SerialNumber'
        /// </summary>
        [Fact]
        public void SerialNumberTest()
        {
            // TODO unit test for the property 'SerialNumber'
        }


    }

}


