// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0
//
// Code generated with OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Vault.Api;
using Vault.Model;
using Vault.Client;
using System.Reflection;
using Newtonsoft.Json;



namespace Vault.Test.Model
{
    /// <summary>
    ///  Class for testing PkiGenerateInternalKeyResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PkiGenerateInternalKeyResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PkiGenerateInternalKeyResponse
        //private PkiGenerateInternalKeyResponse instance;

        public PkiGenerateInternalKeyResponseTests()
        {
            // TODO uncomment below to create an instance of PkiGenerateInternalKeyResponse
            //instance = new PkiGenerateInternalKeyResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PkiGenerateInternalKeyResponse
        /// </summary>
        [Fact]
        public void PkiGenerateInternalKeyResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" PkiGenerateInternalKeyResponse
            //Assert.IsType<PkiGenerateInternalKeyResponse>(instance);
        }




        /// <summary>
        /// Test the property 'KeyId'
        /// </summary>
        [Fact]
        public void KeyIdTest()
        {
            // TODO unit test for the property 'KeyId'
        }

        /// <summary>
        /// Test the property 'KeyName'
        /// </summary>
        [Fact]
        public void KeyNameTest()
        {
            // TODO unit test for the property 'KeyName'
        }

        /// <summary>
        /// Test the property 'KeyType'
        /// </summary>
        [Fact]
        public void KeyTypeTest()
        {
            // TODO unit test for the property 'KeyType'
        }

        /// <summary>
        /// Test the property 'PrivateKey'
        /// </summary>
        [Fact]
        public void PrivateKeyTest()
        {
            // TODO unit test for the property 'PrivateKey'
        }


    }

}


