// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0
//
// Code generated with OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Vault.Api;
using Vault.Model;
using Vault.Client;
using System.Reflection;
using Newtonsoft.Json;



namespace Vault.Test.Model
{
    /// <summary>
    ///  Class for testing PkiIssuerSignVerbatimWithRoleRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PkiIssuerSignVerbatimWithRoleRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PkiIssuerSignVerbatimWithRoleRequest
        //private PkiIssuerSignVerbatimWithRoleRequest instance;

        public PkiIssuerSignVerbatimWithRoleRequestTests()
        {
            // TODO uncomment below to create an instance of PkiIssuerSignVerbatimWithRoleRequest
            //instance = new PkiIssuerSignVerbatimWithRoleRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PkiIssuerSignVerbatimWithRoleRequest
        /// </summary>
        [Fact]
        public void PkiIssuerSignVerbatimWithRoleRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" PkiIssuerSignVerbatimWithRoleRequest
            //Assert.IsType<PkiIssuerSignVerbatimWithRoleRequest>(instance);
        }




        /// <summary>
        /// Test the property 'AltNames'
        /// </summary>
        [Fact]
        public void AltNamesTest()
        {
            // TODO unit test for the property 'AltNames'
        }

        /// <summary>
        /// Test the property 'CommonName'
        /// </summary>
        [Fact]
        public void CommonNameTest()
        {
            // TODO unit test for the property 'CommonName'
        }

        /// <summary>
        /// Test the property 'Csr'
        /// </summary>
        [Fact]
        public void CsrTest()
        {
            // TODO unit test for the property 'Csr'
        }

        /// <summary>
        /// Test the property 'ExcludeCnFromSans'
        /// </summary>
        [Fact]
        public void ExcludeCnFromSansTest()
        {
            // TODO unit test for the property 'ExcludeCnFromSans'
        }

        /// <summary>
        /// Test the property 'ExtKeyUsage'
        /// </summary>
        [Fact]
        public void ExtKeyUsageTest()
        {
            // TODO unit test for the property 'ExtKeyUsage'
        }

        /// <summary>
        /// Test the property 'ExtKeyUsageOids'
        /// </summary>
        [Fact]
        public void ExtKeyUsageOidsTest()
        {
            // TODO unit test for the property 'ExtKeyUsageOids'
        }

        /// <summary>
        /// Test the property 'Format'
        /// </summary>
        [Fact]
        public void FormatTest()
        {
            // TODO unit test for the property 'Format'
        }

        /// <summary>
        /// Test the property 'IpSans'
        /// </summary>
        [Fact]
        public void IpSansTest()
        {
            // TODO unit test for the property 'IpSans'
        }

        /// <summary>
        /// Test the property 'KeyUsage'
        /// </summary>
        [Fact]
        public void KeyUsageTest()
        {
            // TODO unit test for the property 'KeyUsage'
        }

        /// <summary>
        /// Test the property 'NotAfter'
        /// </summary>
        [Fact]
        public void NotAfterTest()
        {
            // TODO unit test for the property 'NotAfter'
        }

        /// <summary>
        /// Test the property 'OtherSans'
        /// </summary>
        [Fact]
        public void OtherSansTest()
        {
            // TODO unit test for the property 'OtherSans'
        }

        /// <summary>
        /// Test the property 'PrivateKeyFormat'
        /// </summary>
        [Fact]
        public void PrivateKeyFormatTest()
        {
            // TODO unit test for the property 'PrivateKeyFormat'
        }

        /// <summary>
        /// Test the property 'RemoveRootsFromChain'
        /// </summary>
        [Fact]
        public void RemoveRootsFromChainTest()
        {
            // TODO unit test for the property 'RemoveRootsFromChain'
        }

        /// <summary>
        /// Test the property 'SerialNumber'
        /// </summary>
        [Fact]
        public void SerialNumberTest()
        {
            // TODO unit test for the property 'SerialNumber'
        }

        /// <summary>
        /// Test the property 'SignatureBits'
        /// </summary>
        [Fact]
        public void SignatureBitsTest()
        {
            // TODO unit test for the property 'SignatureBits'
        }

        /// <summary>
        /// Test the property 'Ttl'
        /// </summary>
        [Fact]
        public void TtlTest()
        {
            // TODO unit test for the property 'Ttl'
        }

        /// <summary>
        /// Test the property 'UriSans'
        /// </summary>
        [Fact]
        public void UriSansTest()
        {
            // TODO unit test for the property 'UriSans'
        }

        /// <summary>
        /// Test the property 'UsePss'
        /// </summary>
        [Fact]
        public void UsePssTest()
        {
            // TODO unit test for the property 'UsePss'
        }

        /// <summary>
        /// Test the property 'UserIds'
        /// </summary>
        [Fact]
        public void UserIdsTest()
        {
            // TODO unit test for the property 'UserIds'
        }


    }

}


