// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0
//
// Code generated with OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Vault.Api;
using Vault.Model;
using Vault.Client;
using System.Reflection;
using Newtonsoft.Json;



namespace Vault.Test.Model
{
    /// <summary>
    ///  Class for testing PkiRevokeRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PkiRevokeRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PkiRevokeRequest
        //private PkiRevokeRequest instance;

        public PkiRevokeRequestTests()
        {
            // TODO uncomment below to create an instance of PkiRevokeRequest
            //instance = new PkiRevokeRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PkiRevokeRequest
        /// </summary>
        [Fact]
        public void PkiRevokeRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" PkiRevokeRequest
            //Assert.IsType<PkiRevokeRequest>(instance);
        }




        /// <summary>
        /// Test the property 'Certificate'
        /// </summary>
        [Fact]
        public void CertificateTest()
        {
            // TODO unit test for the property 'Certificate'
        }

        /// <summary>
        /// Test the property 'SerialNumber'
        /// </summary>
        [Fact]
        public void SerialNumberTest()
        {
            // TODO unit test for the property 'SerialNumber'
        }


    }

}


