// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0
//
// Code generated with OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Vault.Api;
using Vault.Model;
using Vault.Client;
using System.Reflection;
using Newtonsoft.Json;



namespace Vault.Test.Model
{
    /// <summary>
    ///  Class for testing PkiRootSignIntermediateResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PkiRootSignIntermediateResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PkiRootSignIntermediateResponse
        //private PkiRootSignIntermediateResponse instance;

        public PkiRootSignIntermediateResponseTests()
        {
            // TODO uncomment below to create an instance of PkiRootSignIntermediateResponse
            //instance = new PkiRootSignIntermediateResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PkiRootSignIntermediateResponse
        /// </summary>
        [Fact]
        public void PkiRootSignIntermediateResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" PkiRootSignIntermediateResponse
            //Assert.IsType<PkiRootSignIntermediateResponse>(instance);
        }




        /// <summary>
        /// Test the property 'CaChain'
        /// </summary>
        [Fact]
        public void CaChainTest()
        {
            // TODO unit test for the property 'CaChain'
        }

        /// <summary>
        /// Test the property 'Certificate'
        /// </summary>
        [Fact]
        public void CertificateTest()
        {
            // TODO unit test for the property 'Certificate'
        }

        /// <summary>
        /// Test the property 'Expiration'
        /// </summary>
        [Fact]
        public void ExpirationTest()
        {
            // TODO unit test for the property 'Expiration'
        }

        /// <summary>
        /// Test the property 'IssuingCa'
        /// </summary>
        [Fact]
        public void IssuingCaTest()
        {
            // TODO unit test for the property 'IssuingCa'
        }

        /// <summary>
        /// Test the property 'SerialNumber'
        /// </summary>
        [Fact]
        public void SerialNumberTest()
        {
            // TODO unit test for the property 'SerialNumber'
        }


    }

}


