// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0
//
// Code generated with OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Vault.Api;
using Vault.Model;
using Vault.Client;
using System.Reflection;
using Newtonsoft.Json;



namespace Vault.Test.Model
{
    /// <summary>
    ///  Class for testing PkiReplaceRootRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PkiReplaceRootRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PkiReplaceRootRequest
        //private PkiReplaceRootRequest instance;

        public PkiReplaceRootRequestTests()
        {
            // TODO uncomment below to create an instance of PkiReplaceRootRequest
            //instance = new PkiReplaceRootRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PkiReplaceRootRequest
        /// </summary>
        [Fact]
        public void PkiReplaceRootRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" PkiReplaceRootRequest
            //Assert.IsType<PkiReplaceRootRequest>(instance);
        }




        /// <summary>
        /// Test the property 'Default'
        /// </summary>
        [Fact]
        public void DefaultTest()
        {
            // TODO unit test for the property 'Default'
        }


    }

}


