/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.12.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Vault.Api;
using Vault.Model;
using Vault.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Vault.Test.Model
{
    /// <summary>
    ///  Class for testing PkiSignVerbatimRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PkiSignVerbatimRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PkiSignVerbatimRequest
        //private PkiSignVerbatimRequest instance;

        public PkiSignVerbatimRequestTests()
        {
            // TODO uncomment below to create an instance of PkiSignVerbatimRequest
            //instance = new PkiSignVerbatimRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PkiSignVerbatimRequest
        /// </summary>
        [Fact]
        public void PkiSignVerbatimRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" PkiSignVerbatimRequest
            //Assert.IsType<PkiSignVerbatimRequest>(instance);
        }


        /// <summary>
        /// Test the property 'AltNames'
        /// </summary>
        [Fact]
        public void AltNamesTest()
        {
            // TODO unit test for the property 'AltNames'
        }
        /// <summary>
        /// Test the property 'CommonName'
        /// </summary>
        [Fact]
        public void CommonNameTest()
        {
            // TODO unit test for the property 'CommonName'
        }
        /// <summary>
        /// Test the property 'Csr'
        /// </summary>
        [Fact]
        public void CsrTest()
        {
            // TODO unit test for the property 'Csr'
        }
        /// <summary>
        /// Test the property 'ExcludeCnFromSans'
        /// </summary>
        [Fact]
        public void ExcludeCnFromSansTest()
        {
            // TODO unit test for the property 'ExcludeCnFromSans'
        }
        /// <summary>
        /// Test the property 'ExtKeyUsage'
        /// </summary>
        [Fact]
        public void ExtKeyUsageTest()
        {
            // TODO unit test for the property 'ExtKeyUsage'
        }
        /// <summary>
        /// Test the property 'ExtKeyUsageOids'
        /// </summary>
        [Fact]
        public void ExtKeyUsageOidsTest()
        {
            // TODO unit test for the property 'ExtKeyUsageOids'
        }
        /// <summary>
        /// Test the property 'Format'
        /// </summary>
        [Fact]
        public void FormatTest()
        {
            // TODO unit test for the property 'Format'
        }
        /// <summary>
        /// Test the property 'IpSans'
        /// </summary>
        [Fact]
        public void IpSansTest()
        {
            // TODO unit test for the property 'IpSans'
        }
        /// <summary>
        /// Test the property 'IssuerRef'
        /// </summary>
        [Fact]
        public void IssuerRefTest()
        {
            // TODO unit test for the property 'IssuerRef'
        }
        /// <summary>
        /// Test the property 'KeyUsage'
        /// </summary>
        [Fact]
        public void KeyUsageTest()
        {
            // TODO unit test for the property 'KeyUsage'
        }
        /// <summary>
        /// Test the property 'NotAfter'
        /// </summary>
        [Fact]
        public void NotAfterTest()
        {
            // TODO unit test for the property 'NotAfter'
        }
        /// <summary>
        /// Test the property 'OtherSans'
        /// </summary>
        [Fact]
        public void OtherSansTest()
        {
            // TODO unit test for the property 'OtherSans'
        }
        /// <summary>
        /// Test the property 'PrivateKeyFormat'
        /// </summary>
        [Fact]
        public void PrivateKeyFormatTest()
        {
            // TODO unit test for the property 'PrivateKeyFormat'
        }
        /// <summary>
        /// Test the property 'Role'
        /// </summary>
        [Fact]
        public void RoleTest()
        {
            // TODO unit test for the property 'Role'
        }
        /// <summary>
        /// Test the property 'SerialNumber'
        /// </summary>
        [Fact]
        public void SerialNumberTest()
        {
            // TODO unit test for the property 'SerialNumber'
        }
        /// <summary>
        /// Test the property 'Ttl'
        /// </summary>
        [Fact]
        public void TtlTest()
        {
            // TODO unit test for the property 'Ttl'
        }
        /// <summary>
        /// Test the property 'UriSans'
        /// </summary>
        [Fact]
        public void UriSansTest()
        {
            // TODO unit test for the property 'UriSans'
        }

    }

}
