// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0
//
// Code generated with OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Vault.Api;
using Vault.Model;
using Vault.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Vault.Test.Model
{
    /// <summary>
    ///  Class for testing PKIWriteIntermediateSetSignedRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PKIWriteIntermediateSetSignedRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PKIWriteIntermediateSetSignedRequest
        //private PKIWriteIntermediateSetSignedRequest instance;

        public PKIWriteIntermediateSetSignedRequestTests()
        {
            // TODO uncomment below to create an instance of PKIWriteIntermediateSetSignedRequest
            //instance = new PKIWriteIntermediateSetSignedRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PKIWriteIntermediateSetSignedRequest
        /// </summary>
        [Fact]
        public void PKIWriteIntermediateSetSignedRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" PKIWriteIntermediateSetSignedRequest
            //Assert.IsType<PKIWriteIntermediateSetSignedRequest>(instance);
        }


        /// <summary>
        /// Test the property 'Certificate'
        /// </summary>
        [Fact]
        public void CertificateTest()
        {
            // TODO unit test for the property 'Certificate'
        }

    }

}
