// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0
//
// Code generated with OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Vault.Api;
using Vault.Model;
using Vault.Client;
using System.Reflection;
using Newtonsoft.Json;



namespace Vault.Test.Model
{
    /// <summary>
    ///  Class for testing PluginsCatalogListPluginsWithTypeResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PluginsCatalogListPluginsWithTypeResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PluginsCatalogListPluginsWithTypeResponse
        //private PluginsCatalogListPluginsWithTypeResponse instance;

        public PluginsCatalogListPluginsWithTypeResponseTests()
        {
            // TODO uncomment below to create an instance of PluginsCatalogListPluginsWithTypeResponse
            //instance = new PluginsCatalogListPluginsWithTypeResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PluginsCatalogListPluginsWithTypeResponse
        /// </summary>
        [Fact]
        public void PluginsCatalogListPluginsWithTypeResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" PluginsCatalogListPluginsWithTypeResponse
            //Assert.IsType<PluginsCatalogListPluginsWithTypeResponse>(instance);
        }




        /// <summary>
        /// Test the property 'Keys'
        /// </summary>
        [Fact]
        public void KeysTest()
        {
            // TODO unit test for the property 'Keys'
        }


    }

}


