// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0
//
// Code generated with OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Vault.Api;
using Vault.Model;
using Vault.Client;
using System.Reflection;
using Newtonsoft.Json;



namespace Vault.Test.Model
{
    /// <summary>
    ///  Class for testing PluginsCatalogReadPluginConfigurationResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PluginsCatalogReadPluginConfigurationResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PluginsCatalogReadPluginConfigurationResponse
        //private PluginsCatalogReadPluginConfigurationResponse instance;

        public PluginsCatalogReadPluginConfigurationResponseTests()
        {
            // TODO uncomment below to create an instance of PluginsCatalogReadPluginConfigurationResponse
            //instance = new PluginsCatalogReadPluginConfigurationResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PluginsCatalogReadPluginConfigurationResponse
        /// </summary>
        [Fact]
        public void PluginsCatalogReadPluginConfigurationResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" PluginsCatalogReadPluginConfigurationResponse
            //Assert.IsType<PluginsCatalogReadPluginConfigurationResponse>(instance);
        }




        /// <summary>
        /// Test the property 'Args'
        /// </summary>
        [Fact]
        public void ArgsTest()
        {
            // TODO unit test for the property 'Args'
        }

        /// <summary>
        /// Test the property 'Builtin'
        /// </summary>
        [Fact]
        public void BuiltinTest()
        {
            // TODO unit test for the property 'Builtin'
        }

        /// <summary>
        /// Test the property 'Command'
        /// </summary>
        [Fact]
        public void CommandTest()
        {
            // TODO unit test for the property 'Command'
        }

        /// <summary>
        /// Test the property 'DeprecationStatus'
        /// </summary>
        [Fact]
        public void DeprecationStatusTest()
        {
            // TODO unit test for the property 'DeprecationStatus'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Sha256'
        /// </summary>
        [Fact]
        public void Sha256Test()
        {
            // TODO unit test for the property 'Sha256'
        }

        /// <summary>
        /// Test the property '_Version'
        /// </summary>
        [Fact]
        public void _VersionTest()
        {
            // TODO unit test for the property '_Version'
        }


    }

}


