// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0
//
// Code generated with OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Vault.Api;
using Vault.Model;
using Vault.Client;
using System.Reflection;
using Newtonsoft.Json;



namespace Vault.Test.Model
{
    /// <summary>
    ///  Class for testing PluginsReloadBackendsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PluginsReloadBackendsResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PluginsReloadBackendsResponse
        //private PluginsReloadBackendsResponse instance;

        public PluginsReloadBackendsResponseTests()
        {
            // TODO uncomment below to create an instance of PluginsReloadBackendsResponse
            //instance = new PluginsReloadBackendsResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PluginsReloadBackendsResponse
        /// </summary>
        [Fact]
        public void PluginsReloadBackendsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" PluginsReloadBackendsResponse
            //Assert.IsType<PluginsReloadBackendsResponse>(instance);
        }




        /// <summary>
        /// Test the property 'ReloadId'
        /// </summary>
        [Fact]
        public void ReloadIdTest()
        {
            // TODO unit test for the property 'ReloadId'
        }


    }

}


