// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0
//
// Code generated with OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Vault.Api;
using Vault.Model;
using Vault.Client;
using System.Reflection;
using Newtonsoft.Json;



namespace Vault.Test.Model
{
    /// <summary>
    ///  Class for testing RadiusConfigureRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RadiusConfigureRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RadiusConfigureRequest
        //private RadiusConfigureRequest instance;

        public RadiusConfigureRequestTests()
        {
            // TODO uncomment below to create an instance of RadiusConfigureRequest
            //instance = new RadiusConfigureRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RadiusConfigureRequest
        /// </summary>
        [Fact]
        public void RadiusConfigureRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" RadiusConfigureRequest
            //Assert.IsType<RadiusConfigureRequest>(instance);
        }




        /// <summary>
        /// Test the property 'DialTimeout'
        /// </summary>
        [Fact]
        public void DialTimeoutTest()
        {
            // TODO unit test for the property 'DialTimeout'
        }

        /// <summary>
        /// Test the property 'Host'
        /// </summary>
        [Fact]
        public void HostTest()
        {
            // TODO unit test for the property 'Host'
        }

        /// <summary>
        /// Test the property 'NasIdentifier'
        /// </summary>
        [Fact]
        public void NasIdentifierTest()
        {
            // TODO unit test for the property 'NasIdentifier'
        }

        /// <summary>
        /// Test the property 'NasPort'
        /// </summary>
        [Fact]
        public void NasPortTest()
        {
            // TODO unit test for the property 'NasPort'
        }

        /// <summary>
        /// Test the property 'Port'
        /// </summary>
        [Fact]
        public void PortTest()
        {
            // TODO unit test for the property 'Port'
        }

        /// <summary>
        /// Test the property 'ReadTimeout'
        /// </summary>
        [Fact]
        public void ReadTimeoutTest()
        {
            // TODO unit test for the property 'ReadTimeout'
        }

        /// <summary>
        /// Test the property 'Secret'
        /// </summary>
        [Fact]
        public void SecretTest()
        {
            // TODO unit test for the property 'Secret'
        }

        /// <summary>
        /// Test the property 'TokenBoundCidrs'
        /// </summary>
        [Fact]
        public void TokenBoundCidrsTest()
        {
            // TODO unit test for the property 'TokenBoundCidrs'
        }

        /// <summary>
        /// Test the property 'TokenExplicitMaxTtl'
        /// </summary>
        [Fact]
        public void TokenExplicitMaxTtlTest()
        {
            // TODO unit test for the property 'TokenExplicitMaxTtl'
        }

        /// <summary>
        /// Test the property 'TokenMaxTtl'
        /// </summary>
        [Fact]
        public void TokenMaxTtlTest()
        {
            // TODO unit test for the property 'TokenMaxTtl'
        }

        /// <summary>
        /// Test the property 'TokenNoDefaultPolicy'
        /// </summary>
        [Fact]
        public void TokenNoDefaultPolicyTest()
        {
            // TODO unit test for the property 'TokenNoDefaultPolicy'
        }

        /// <summary>
        /// Test the property 'TokenNumUses'
        /// </summary>
        [Fact]
        public void TokenNumUsesTest()
        {
            // TODO unit test for the property 'TokenNumUses'
        }

        /// <summary>
        /// Test the property 'TokenPeriod'
        /// </summary>
        [Fact]
        public void TokenPeriodTest()
        {
            // TODO unit test for the property 'TokenPeriod'
        }

        /// <summary>
        /// Test the property 'TokenPolicies'
        /// </summary>
        [Fact]
        public void TokenPoliciesTest()
        {
            // TODO unit test for the property 'TokenPolicies'
        }

        /// <summary>
        /// Test the property 'TokenTtl'
        /// </summary>
        [Fact]
        public void TokenTtlTest()
        {
            // TODO unit test for the property 'TokenTtl'
        }

        /// <summary>
        /// Test the property 'TokenType'
        /// </summary>
        [Fact]
        public void TokenTypeTest()
        {
            // TODO unit test for the property 'TokenType'
        }

        /// <summary>
        /// Test the property 'UnregisteredUserPolicies'
        /// </summary>
        [Fact]
        public void UnregisteredUserPoliciesTest()
        {
            // TODO unit test for the property 'UnregisteredUserPolicies'
        }


    }

}


