// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0
//
// Code generated with OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Vault.Api;
using Vault.Model;
using Vault.Client;
using System.Reflection;
using Newtonsoft.Json;



namespace Vault.Test.Model
{
    /// <summary>
    ///  Class for testing RawWritePathRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RawWritePathRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RawWritePathRequest
        //private RawWritePathRequest instance;

        public RawWritePathRequestTests()
        {
            // TODO uncomment below to create an instance of RawWritePathRequest
            //instance = new RawWritePathRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RawWritePathRequest
        /// </summary>
        [Fact]
        public void RawWritePathRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" RawWritePathRequest
            //Assert.IsType<RawWritePathRequest>(instance);
        }




        /// <summary>
        /// Test the property 'Compressed'
        /// </summary>
        [Fact]
        public void CompressedTest()
        {
            // TODO unit test for the property 'Compressed'
        }

        /// <summary>
        /// Test the property 'CompressionType'
        /// </summary>
        [Fact]
        public void CompressionTypeTest()
        {
            // TODO unit test for the property 'CompressionType'
        }

        /// <summary>
        /// Test the property 'Encoding'
        /// </summary>
        [Fact]
        public void EncodingTest()
        {
            // TODO unit test for the property 'Encoding'
        }

        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }


    }

}


