// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0
//
// Code generated with OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Vault.Api;
using Vault.Model;
using Vault.Client;
using System.Reflection;
using Newtonsoft.Json;



namespace Vault.Test.Model
{
    /// <summary>
    ///  Class for testing SshVerifyOtpRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SshVerifyOtpRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SshVerifyOtpRequest
        //private SshVerifyOtpRequest instance;

        public SshVerifyOtpRequestTests()
        {
            // TODO uncomment below to create an instance of SshVerifyOtpRequest
            //instance = new SshVerifyOtpRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SshVerifyOtpRequest
        /// </summary>
        [Fact]
        public void SshVerifyOtpRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" SshVerifyOtpRequest
            //Assert.IsType<SshVerifyOtpRequest>(instance);
        }




        /// <summary>
        /// Test the property 'Otp'
        /// </summary>
        [Fact]
        public void OtpTest()
        {
            // TODO unit test for the property 'Otp'
        }


    }

}


