// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0
//
// Code generated with OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Vault.Api;
using Vault.Model;
using Vault.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Vault.Test.Model
{
    /// <summary>
    ///  Class for testing SSHWriteZeroAddressConfigRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SSHWriteZeroAddressConfigRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SSHWriteZeroAddressConfigRequest
        //private SSHWriteZeroAddressConfigRequest instance;

        public SSHWriteZeroAddressConfigRequestTests()
        {
            // TODO uncomment below to create an instance of SSHWriteZeroAddressConfigRequest
            //instance = new SSHWriteZeroAddressConfigRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SSHWriteZeroAddressConfigRequest
        /// </summary>
        [Fact]
        public void SSHWriteZeroAddressConfigRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" SSHWriteZeroAddressConfigRequest
            //Assert.IsType<SSHWriteZeroAddressConfigRequest>(instance);
        }


        /// <summary>
        /// Test the property 'Roles'
        /// </summary>
        [Fact]
        public void RolesTest()
        {
            // TODO unit test for the property 'Roles'
        }

    }

}
