// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0
//
// Code generated with OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Vault.Api;
using Vault.Model;
using Vault.Client;
using System.Reflection;
using Newtonsoft.Json;



namespace Vault.Test.Model
{
    /// <summary>
    ///  Class for testing TokenRenewRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TokenRenewRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TokenRenewRequest
        //private TokenRenewRequest instance;

        public TokenRenewRequestTests()
        {
            // TODO uncomment below to create an instance of TokenRenewRequest
            //instance = new TokenRenewRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TokenRenewRequest
        /// </summary>
        [Fact]
        public void TokenRenewRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" TokenRenewRequest
            //Assert.IsType<TokenRenewRequest>(instance);
        }




        /// <summary>
        /// Test the property 'Increment'
        /// </summary>
        [Fact]
        public void IncrementTest()
        {
            // TODO unit test for the property 'Increment'
        }

        /// <summary>
        /// Test the property 'Token'
        /// </summary>
        [Fact]
        public void TokenTest()
        {
            // TODO unit test for the property 'Token'
        }


    }

}


