// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0
//
// Code generated with OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Vault.Api;
using Vault.Model;
using Vault.Client;
using System.Reflection;
using Newtonsoft.Json;



namespace Vault.Test.Model
{
    /// <summary>
    ///  Class for testing TransitTrimKeyRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TransitTrimKeyRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TransitTrimKeyRequest
        //private TransitTrimKeyRequest instance;

        public TransitTrimKeyRequestTests()
        {
            // TODO uncomment below to create an instance of TransitTrimKeyRequest
            //instance = new TransitTrimKeyRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TransitTrimKeyRequest
        /// </summary>
        [Fact]
        public void TransitTrimKeyRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" TransitTrimKeyRequest
            //Assert.IsType<TransitTrimKeyRequest>(instance);
        }




        /// <summary>
        /// Test the property 'MinAvailableVersion'
        /// </summary>
        [Fact]
        public void MinAvailableVersionTest()
        {
            // TODO unit test for the property 'MinAvailableVersion'
        }


    }

}


