// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0
//
// Code generated with OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Vault.Api;
using Vault.Model;
using Vault.Client;
using System.Reflection;
using Newtonsoft.Json;



namespace Vault.Test.Model
{
    /// <summary>
    ///  Class for testing TransitRotateKeyRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TransitRotateKeyRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TransitRotateKeyRequest
        //private TransitRotateKeyRequest instance;

        public TransitRotateKeyRequestTests()
        {
            // TODO uncomment below to create an instance of TransitRotateKeyRequest
            //instance = new TransitRotateKeyRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TransitRotateKeyRequest
        /// </summary>
        [Fact]
        public void TransitRotateKeyRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" TransitRotateKeyRequest
            //Assert.IsType<TransitRotateKeyRequest>(instance);
        }




        /// <summary>
        /// Test the property 'ManagedKeyId'
        /// </summary>
        [Fact]
        public void ManagedKeyIdTest()
        {
            // TODO unit test for the property 'ManagedKeyId'
        }

        /// <summary>
        /// Test the property 'ManagedKeyName'
        /// </summary>
        [Fact]
        public void ManagedKeyNameTest()
        {
            // TODO unit test for the property 'ManagedKeyName'
        }


    }

}


