// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0
//
// Code generated with OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Vault.Api;
using Vault.Model;
using Vault.Client;
using System.Reflection;
using Newtonsoft.Json;



namespace Vault.Test.Model
{
    /// <summary>
    ///  Class for testing TransitConfigureCacheRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TransitConfigureCacheRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TransitConfigureCacheRequest
        //private TransitConfigureCacheRequest instance;

        public TransitConfigureCacheRequestTests()
        {
            // TODO uncomment below to create an instance of TransitConfigureCacheRequest
            //instance = new TransitConfigureCacheRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TransitConfigureCacheRequest
        /// </summary>
        [Fact]
        public void TransitConfigureCacheRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" TransitConfigureCacheRequest
            //Assert.IsType<TransitConfigureCacheRequest>(instance);
        }




        /// <summary>
        /// Test the property 'Size'
        /// </summary>
        [Fact]
        public void SizeTest()
        {
            // TODO unit test for the property 'Size'
        }


    }

}


