// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0
//
// Code generated with OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Vault.Api;
using Vault.Model;
using Vault.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Vault.Test.Model
{
    /// <summary>
    ///  Class for testing UserpassLoginRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UserpassLoginRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UserpassLoginRequest
        //private UserpassLoginRequest instance;

        public UserpassLoginRequestTests()
        {
            // TODO uncomment below to create an instance of UserpassLoginRequest
            //instance = new UserpassLoginRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UserpassLoginRequest
        /// </summary>
        [Fact]
        public void UserpassLoginRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" UserpassLoginRequest
            //Assert.IsType<UserpassLoginRequest>(instance);
        }


        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Fact]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }

    }

}
