/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.13.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Vault.Api;
using Vault.Model;
using Vault.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Vault.Test.Model
{
    /// <summary>
    ///  Class for testing UserpassUsersPasswordRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UserpassUsersPasswordRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UserpassUsersPasswordRequest
        //private UserpassUsersPasswordRequest instance;

        public UserpassUsersPasswordRequestTests()
        {
            // TODO uncomment below to create an instance of UserpassUsersPasswordRequest
            //instance = new UserpassUsersPasswordRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UserpassUsersPasswordRequest
        /// </summary>
        [Fact]
        public void UserpassUsersPasswordRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" UserpassUsersPasswordRequest
            //Assert.IsType<UserpassUsersPasswordRequest>(instance);
        }


        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Fact]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }

    }

}
