// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.13.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Vault.Api;
using Vault.Model;
using Vault.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Vault.Test.Model
{
    /// <summary>
    ///  Class for testing WriteCapabilitiesAccessorRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WriteCapabilitiesAccessorRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WriteCapabilitiesAccessorRequest
        //private WriteCapabilitiesAccessorRequest instance;

        public WriteCapabilitiesAccessorRequestTests()
        {
            // TODO uncomment below to create an instance of WriteCapabilitiesAccessorRequest
            //instance = new WriteCapabilitiesAccessorRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WriteCapabilitiesAccessorRequest
        /// </summary>
        [Fact]
        public void WriteCapabilitiesAccessorRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" WriteCapabilitiesAccessorRequest
            //Assert.IsType<WriteCapabilitiesAccessorRequest>(instance);
        }


        /// <summary>
        /// Test the property 'Accessor'
        /// </summary>
        [Fact]
        public void AccessorTest()
        {
            // TODO unit test for the property 'Accessor'
        }
        /// <summary>
        /// Test the property 'Path'
        /// </summary>
        [Fact]
        public void PathTest()
        {
            // TODO unit test for the property 'Path'
        }
        /// <summary>
        /// Test the property 'Paths'
        /// </summary>
        [Fact]
        public void PathsTest()
        {
            // TODO unit test for the property 'Paths'
        }

    }

}
