# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

additionalProperties:
  supportsRetry: true
  packageAuthors: Vault DevEx
  packageCompany: Hashicorp
  packageName: Vault
  packageVersion: 0.2.0
  packageGuid: "{16184629-2991-4084-BCA4-2748275C24E5}"
library: httpclient
files:
  Client.mustache:
    destinationFilename: src/Vault/VaultClient.cs
    templateType: SupportingFiles
  RateLimitConfiguration.mustache:
    destinationFilename: src/Vault/Client/RateLimitConfiguration.cs
    templateType: SupportingFiles
  Response.mustache:
    destinationFilename: src/Vault/Client/Response.cs
    templateType: SupportingFiles
