additionalProperties:
  supportsRetry: false
  packageName: Vault
  packageVersion: 0.0.1
library: httpclient
files:
  Client.mustache:
    destinationFilename: src/VaultClient.cs
    templateType: SupportingFiles