additionalProperties:
  supportsRetry: true
  packageName: Vault
  packageVersion: 0.0.1
library: httpclient
files:
  Client.mustache:
    destinationFilename: src/Vault/VaultClient.cs
    templateType: SupportingFiles
  RateLimitConfiguration.mustache:
    destinationFilename: src/Vault/Client/RateLimitConfiguration.cs
    templateType: SupportingFiles
  Response.mustache:
    destinationFilename: src/Vault/Client/Response.cs
    templateType: SupportingFiles
