/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.12.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using VaultClient.Api;
using VaultClient.Model;
using VaultClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace VaultClient.Test.Model
{
    /// <summary>
    ///  Class for testing ConsulRolesRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ConsulRolesRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ConsulRolesRequest
        //private ConsulRolesRequest instance;

        public ConsulRolesRequestTests()
        {
            // TODO uncomment below to create an instance of ConsulRolesRequest
            //instance = new ConsulRolesRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ConsulRolesRequest
        /// </summary>
        [Fact]
        public void ConsulRolesRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" ConsulRolesRequest
            //Assert.IsType<ConsulRolesRequest>(instance);
        }


        /// <summary>
        /// Test the property 'ConsulNamespace'
        /// </summary>
        [Fact]
        public void ConsulNamespaceTest()
        {
            // TODO unit test for the property 'ConsulNamespace'
        }
        /// <summary>
        /// Test the property 'ConsulPolicies'
        /// </summary>
        [Fact]
        public void ConsulPoliciesTest()
        {
            // TODO unit test for the property 'ConsulPolicies'
        }
        /// <summary>
        /// Test the property 'ConsulRoles'
        /// </summary>
        [Fact]
        public void ConsulRolesTest()
        {
            // TODO unit test for the property 'ConsulRoles'
        }
        /// <summary>
        /// Test the property 'Lease'
        /// </summary>
        [Fact]
        public void LeaseTest()
        {
            // TODO unit test for the property 'Lease'
        }
        /// <summary>
        /// Test the property 'Local'
        /// </summary>
        [Fact]
        public void LocalTest()
        {
            // TODO unit test for the property 'Local'
        }
        /// <summary>
        /// Test the property 'MaxTtl'
        /// </summary>
        [Fact]
        public void MaxTtlTest()
        {
            // TODO unit test for the property 'MaxTtl'
        }
        /// <summary>
        /// Test the property 'NodeIdentities'
        /// </summary>
        [Fact]
        public void NodeIdentitiesTest()
        {
            // TODO unit test for the property 'NodeIdentities'
        }
        /// <summary>
        /// Test the property 'Partition'
        /// </summary>
        [Fact]
        public void PartitionTest()
        {
            // TODO unit test for the property 'Partition'
        }
        /// <summary>
        /// Test the property 'Policies'
        /// </summary>
        [Fact]
        public void PoliciesTest()
        {
            // TODO unit test for the property 'Policies'
        }
        /// <summary>
        /// Test the property 'Policy'
        /// </summary>
        [Fact]
        public void PolicyTest()
        {
            // TODO unit test for the property 'Policy'
        }
        /// <summary>
        /// Test the property 'ServiceIdentities'
        /// </summary>
        [Fact]
        public void ServiceIdentitiesTest()
        {
            // TODO unit test for the property 'ServiceIdentities'
        }
        /// <summary>
        /// Test the property 'TokenType'
        /// </summary>
        [Fact]
        public void TokenTypeTest()
        {
            // TODO unit test for the property 'TokenType'
        }
        /// <summary>
        /// Test the property 'Ttl'
        /// </summary>
        [Fact]
        public void TtlTest()
        {
            // TODO unit test for the property 'Ttl'
        }

    }

}
