/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.12.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using VaultClient.Api;
using VaultClient.Model;
using VaultClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace VaultClient.Test.Model
{
    /// <summary>
    ///  Class for testing GcpkmsKeysConfigRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GcpkmsKeysConfigRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GcpkmsKeysConfigRequest
        //private GcpkmsKeysConfigRequest instance;

        public GcpkmsKeysConfigRequestTests()
        {
            // TODO uncomment below to create an instance of GcpkmsKeysConfigRequest
            //instance = new GcpkmsKeysConfigRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GcpkmsKeysConfigRequest
        /// </summary>
        [Fact]
        public void GcpkmsKeysConfigRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" GcpkmsKeysConfigRequest
            //Assert.IsType<GcpkmsKeysConfigRequest>(instance);
        }


        /// <summary>
        /// Test the property 'MaxVersion'
        /// </summary>
        [Fact]
        public void MaxVersionTest()
        {
            // TODO unit test for the property 'MaxVersion'
        }
        /// <summary>
        /// Test the property 'MinVersion'
        /// </summary>
        [Fact]
        public void MinVersionTest()
        {
            // TODO unit test for the property 'MinVersion'
        }

    }

}
