/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.11.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using VaultClient.Api;
using VaultClient.Model;
using VaultClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace VaultClient.Test.Model
{
    /// <summary>
    ///  Class for testing IdentityGroupNameRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IdentityGroupNameRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IdentityGroupNameRequest
        //private IdentityGroupNameRequest instance;

        public IdentityGroupNameRequestTests()
        {
            // TODO uncomment below to create an instance of IdentityGroupNameRequest
            //instance = new IdentityGroupNameRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IdentityGroupNameRequest
        /// </summary>
        [Fact]
        public void IdentityGroupNameRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" IdentityGroupNameRequest
            //Assert.IsType<IdentityGroupNameRequest>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'MemberEntityIds'
        /// </summary>
        [Fact]
        public void MemberEntityIdsTest()
        {
            // TODO unit test for the property 'MemberEntityIds'
        }
        /// <summary>
        /// Test the property 'MemberGroupIds'
        /// </summary>
        [Fact]
        public void MemberGroupIdsTest()
        {
            // TODO unit test for the property 'MemberGroupIds'
        }
        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Fact]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }
        /// <summary>
        /// Test the property 'Policies'
        /// </summary>
        [Fact]
        public void PoliciesTest()
        {
            // TODO unit test for the property 'Policies'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
