/*
 * HashiCorp Vault API
 *
 * HTTP API that gives you full access to Vault. All API routes are prefixed with `/v1/`.
 *
 * The version of the OpenAPI document: 1.11.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using VaultClient.Api;
using VaultClient.Model;
using VaultClient.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace VaultClient.Test.Model
{
    /// <summary>
    ///  Class for testing PkiConfigKeysRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PkiConfigKeysRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PkiConfigKeysRequest
        //private PkiConfigKeysRequest instance;

        public PkiConfigKeysRequestTests()
        {
            // TODO uncomment below to create an instance of PkiConfigKeysRequest
            //instance = new PkiConfigKeysRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PkiConfigKeysRequest
        /// </summary>
        [Fact]
        public void PkiConfigKeysRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" PkiConfigKeysRequest
            //Assert.IsType<PkiConfigKeysRequest>(instance);
        }


        /// <summary>
        /// Test the property 'Default'
        /// </summary>
        [Fact]
        public void DefaultTest()
        {
            // TODO unit test for the property 'Default'
        }

    }

}
