name: lint
on:
  pull_request:
    branches: ["**"]

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true

jobs:
  lint_csharp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "6.0.x"

      # Install dotnet format as a global tool
      - name: Install dotnet format
        run: dotnet tool update --global dotnet-format

      - name: Run dotnet format
        run: dotnet format '.\' --folder
