name: ci

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '3.1.x' ]
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal

  check-regen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: install rename utility
        run: sudo apt-get -y install rename
        
      - name: check dotnet version
        run: |
          command -v dotnet
          which -a dotnet
          dotnet --version

      - name: check regenerated files
        run: |
          function read_changed_files() {
            changed_files="$(git diff --stat ':!Vault.sln')"
            if [[ "$changed_files" != "" ]]; then
              echo "found diffs after running 'make regen'"
              echo "please run 'make regen' & commit the changed files:"
              echo "$changed_files"
              # exit 1
            fi
          }
          
          make delete-generated
          make generate
          read_changed_files
          make format
          read_changed_files
          make clean
          read_changed_files
          exit 1
          
