name: Release to Nuget

on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v2.0.2

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ["3.1.x"]
    name: Create Release

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
      - name: Create Nuget Package
        run: dotnet pack -c Release -p:PackageVersion=${{ github.event.release.tag_name }} --include-symbols
      - name: Add Artifactory Source
        with: # Pull Artifactory Secrets
          ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER_NAME }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
          ARTIFACTORY_REPO: ${{ secrets.ARTIFACTORY_REPO_URL }}
        run: |
          dotnet nuget sources add -Name Artifactory 
          -Source "$ARTIFACTORY_REPO"
          -username "$ARTIFACTORY_USER"
          -password "$ARTIFACTORY_PASSWORD"
      - name: Push Nuget Package
        run: dotnet nuget push **/*.nupkg -src Artifactory
