name: Release to Nuget

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ["3.1.x"]
    name: Create Release

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
      - name: Create Nuget Package
        run: dotnet pack -c Release -p:PackageVersion=${{ github.event.release.tag_name }} --include-symbols
      - name: Add Artifactory Source
        run: |
          nuget sources add 
          -Name Artifactory 
          -Source ${{ secrets.ARTIFACTORY_REPO_URL }}
          -username ${{ secrets.ARTIFACTORY_USER_NAME }}
          -password ${{ secrets.ARTIFACTORY_PASSWORD }}
      - name: Push Nuget Package
        run: nuget push **/*.nupkg -src Artifactory
