name: Release to Nuget

on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v2.0.2

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      uses: actions/checkout@v3
